### ISSUE TITLE
Fix folder structure naming

### ISSUE THREAD

**Issue by jamieyello** [MNES-Emulator/MNES#11]
They're all caps and it's annoying me.

![image](https://github.com/MNES-Emulator/MNES/assets/10054829/b0c25fc6-db59-44e0-97d2-55b85136dd35)

**Comment by Morbidous** [comment]
I tried doing this but it was very tricky. git and windows are like both half-case-sensitive. I tried it with `git mv` using a temp name but it did not go well. might have to commit the temp names or something.

**Comment by jamieyello** [comment]
> might have to commit the temp names or something.
Yeah that's probably the only way

**Comment by jamieyello** [comment]
Fixed with https://github.com/MNES-Emulator/MNES/commit/69138f91690c96965c0e8c323e3f9a34e0dfa072
