### ISSUE TITLE
Move all file management to a new project

### ISSUE THREAD

**Issue by jamieyello** [MNES-Emulator/MNES#9]
but keep ConfigSettings in the core, aka it doesn't make sense for a standalone core to start creating files. UI projects can reference that as well as the core.

**Comment by Morbidous** [comment]
related to this you should have some kind of `Jamie.Core` where you can put reusable code. but I don't know how that works with git repos especially on github. theoretically you would want to reference that from here, but also have it somewhere that other projects can use. you could have one mega repo to do that but it seems that's not how it's supposed to work. possibly you would publish the shared library as a nuget package and then use a package reference, but I've never tried that so far.

**Comment by jamieyello** [comment]
I was thinking about more of a "common ui" project that all UIs will use, like this https://github.com/MNES-Emulator/MNES/commit/3a91a014f207714366e3b54d9e3d4c8c920850af

If I was to do that I would have a Jamie nuget package, which would seem a bit strange? I take your point that I should have a big library that I re-use over and over
